### PR TITLE
HappyBase as 3 sub-packages

### PR DESCRIPTION
**Pull request by aiudirog**
@wbolster I fleshed out my initial idea of 3 packages in one repo, at least just for the code. Recovering happybase from aiohappybase only took about a half hour. Most of the work was regex find and delete on `(async|await)\s`, lol.

### CODE REVIEW

**Comment by wbolster** [comment]
nice, didn't expect it to be feasible!

**Comment by aiudirog** [comment]
@wbolster, haha yeah it was a little weird on the imports but it did work out. When you get the chance, check out #2 and let me know what you think. It puts everything into 1 package with an aio subpackage.

**Comment by aiudirog** [comment]
I actually have a better idea than #2 : swap the package levels. If aio is the default, 99% of the sync implementation can be automatically generated just by stripping the async/await keywords. There can be a sync subpackage which generates it's methods on the fly (if they aren't already implemented) if someone tries to import it. 

This has a couple of benefits over this PR and #2:
- A huge amount of code duplication is removed in favor of a simple find, delete, and exec at import time and anything that needs to be different can be implemented explicitly.
- We don't need to release a HappyBase v2 that breaks everyone's code if they are on 3.5 or below. I'm sure a lot of projects have something like `happybase>=1.0` in their requirements.txt. We can just leave HappyBase as is and I can move forward with AIOHappyBase while providing a backwards compatible endpoint for people to use.

---
A fun side note: I spent a little too long trying to come up with an `asynchronize()` function (just in my head, no code) for generating the async version on the fly to remove the duplication in the aio subpackage before I realized going the other way would be much, much easier, haha.

**Comment by wbolster** [comment]
cool. fyi, you may be interested in this discussion: https://github.com/encode/httpx/issues/522

**Comment by wbolster** [comment]
i am very happy with you giving happybase some serious :heart:. i've opened https://github.com/python-happybase/happybase/issues/233 to discuss the happybase+aiohappybase, and it would be great if you can chime in over there.

**Comment by aiudirog** [comment]
That discussion is interesting and actually makes me think the last approach, where sync is generated on the fly if people explicitly ask for it, is definitely the way to go. I already mocked up a function to do generate the sync versions of all the classes. The rest is just some declarations.

--------

Sounds great! Thanks for being available to help out with this.

**Comment by aiudirog** [comment]
Closed in favor of #3

**Pull request closed without merging**
